# Generated by Django 5.0.14 on 2026-05-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('venue_type', models.CharField(choices=[('festival', 'Festival'), ('theater', 'Teatro / Auditorio'), ('club', 'Club / Antro'), ('private', 'Evento Privado'), ('other', 'Otro')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Booking Inquiries',
            },
        ),
    ]
