# Generated by Django 5.0.14 on 2026-05-21 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('signature_base64', models.TextField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_signature', models.TextField(blank=True, null=True)),
                ('manager_signed_at', models.DateTimeField(blank=True, null=True)),
                ('is_fully_signed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='bookings.bookinginquiry')),
            ],
        ),
    ]
