services:
  db:
    container_name: ambar_db
    image: postgres:16-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/:Z
    environment:
      - POSTGRES_DB=${DB_NAME:-msambar}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    ports:
      - "5435:5432"
    networks:
      - default

  backend:
    container_name: ambar_backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/staticfiles:Z
      - media_volume:/media_files:Z
    environment:
      - STATIC_ROOT=/staticfiles
      - MEDIA_ROOT=/media_files
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - default
      - prod_network

  frontend:
    container_name: ambar_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    restart: always
    networks:
      - default
      - prod_network

volumes:
  postgres_data_prod:
    name: ambar_postgres_data
  static_volume:
    name: ambar_static_volume
  media_volume:
    name: ambar_media_volume

networks:
  prod_network:
    external: true
  default:
    name: ms-ambar_default
