# Generated by Django 5.0.14 on 2026-06-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_newslettersubscriber_post_is_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SESIdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='msambar.com', max_length=255, unique=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending DNS Setup'), ('verified', 'Verified / Active'), ('failed', 'Verification Failed')], default='pending', max_length=50)),
                ('dkim_token_1', models.CharField(blank=True, help_text='CNAME Token 1 Name/Value', max_length=255)),
                ('dkim_token_2', models.CharField(blank=True, help_text='CNAME Token 2 Name/Value', max_length=255)),
                ('dkim_token_3', models.CharField(blank=True, help_text='CNAME Token 3 Name/Value', max_length=255)),
                ('mail_from_domain', models.CharField(default='mail.msambar.com', max_length=255)),
                ('mail_from_mx_target', models.CharField(default='feedback-smtp.us-east-1.amazonses.com', max_length=255)),
                ('spf_record_value', models.CharField(default='v=spf1 include:amazonses.com ~all', max_length=255)),
                ('dmarc_record_value', models.CharField(default='v=DMARC1; p=none; rua=mailto:dmarc-reports@msambar.com', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
