# Generated by Django 5.0.14 on 2026-06-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_sesidentityverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
