# Generated by Django 5.0.14 on 2026-06-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_emailcampaign_font_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='ctas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='image_style',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
