# Generated by Django 5.0.14 on 2026-06-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_emailcampaign_ctas_emailcampaign_image_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTemplateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaign_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='email_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='footer_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
