# Generated by Django 5.0.14 on 2026-06-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_campaigntemplateimage_emailcampaign_email_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='custom_styles',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='footer_font_family',
            field=models.CharField(default='serif', max_length=100),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='title_font_family',
            field=models.CharField(default='serif', max_length=100),
        ),
    ]
