# Generated by Django 5.0.14 on 2026-06-19 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_emailcampaign_custom_styles_and_more'),
        ('tickets', '0012_event_slug_alter_event_doors_open_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_list', to='tickets.event')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='marketing_lists', to='blog.newslettersubscriber')),
            ],
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='marketing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='blog.marketinglist'),
        ),
    ]
