# Generated by Django 5.0.14 on 2026-09-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_category_slug_alter_marketinglist_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='snippet',
            field=models.TextField(blank=True, default='', help_text='Texto de previsualización (snippet/preheader) para clientes de correo.'),
        ),
    ]
