# Generated by Django 5.0.14 on 2026-09-22 06:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_emailcampaign_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEmailQuotaCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='brevo', max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sent_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Email Quota Counter',
                'verbose_name_plural': 'Daily Email Quota Counters',
                'unique_together': {('provider', 'date')},
            },
        ),
    ]
