# Generated by Django 5.1 on 2026-08-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del álbum o EP', max_length=255)),
                ('release_year', models.CharField(default='2026', help_text='Año de lanzamiento', max_length=10)),
                ('cover_url', models.CharField(blank=True, help_text='URL de la carátula / portada', max_length=500, null=True)),
                ('release_date', models.DateField(blank=True, help_text='Fecha de lanzamiento oficial', null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Reseña artística del álbum')),
                ('spotify_url', models.URLField(blank=True, help_text='Enlace directo Spotify', null=True)),
                ('apple_music_url', models.URLField(blank=True, help_text='Enlace directo Apple Music', null=True)),
                ('youtube_url', models.URLField(blank=True, help_text='Enlace a Canal de YouTube', null=True)),
                ('youtube_music_url', models.URLField(blank=True, help_text='Enlace YouTube Music', null=True)),
                ('amazon_music_url', models.URLField(blank=True, help_text='Enlace Amazon Music', null=True)),
                ('spotify_id', models.CharField(blank=True, db_index=True, help_text='ID de álbum en Spotify', max_length=100, null=True, unique=True)),
                ('youtube_id', models.CharField(blank=True, db_index=True, help_text='ID de playlist/album en YouTube', max_length=100, null=True, unique=True)),
                ('itunes_id', models.CharField(blank=True, db_index=True, help_text='ID de colección en iTunes', max_length=100, null=True, unique=True)),
                ('is_featured', models.BooleanField(default=True, help_text='Destacar en portada de discografía')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Álbum',
                'verbose_name_plural': 'Álbumes',
                'ordering': ['-release_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.IntegerField(default=1, help_text='Número de pista en el álbum')),
                ('title', models.CharField(help_text='Nombre de la canción o tema', max_length=255)),
                ('duration_seconds', models.IntegerField(default=210, help_text='Duración en segundos')),
                ('preview_url', models.URLField(blank=True, help_text='URL de audio preview (mp3/stream)', null=True)),
                ('spotify_id', models.CharField(blank=True, db_index=True, help_text='ID de canción en Spotify', max_length=100, null=True, unique=True)),
                ('youtube_id', models.CharField(blank=True, db_index=True, help_text='ID de video en YouTube', max_length=100, null=True, unique=True)),
                ('itunes_id', models.CharField(blank=True, db_index=True, help_text='ID de canción en iTunes', max_length=100, null=True, unique=True)),
                ('is_single', models.BooleanField(default=False, help_text='Marcar si fue lanzada como sencillo')),
                ('play_count', models.PositiveIntegerField(default=0, help_text='Contador de reproducciones en plataforma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album')),
            ],
            options={
                'verbose_name': 'Pista / Canción',
                'verbose_name_plural': 'Pistas / Canciones',
                'ordering': ['track_number', 'id'],
            },
        ),
    ]
