# Generated by Django 5.1 on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discography_description', models.TextField(default='Explora las resonancias místicas, producciones acústicas y sencillos oficiales de Ms. Ambar en todas las plataformas digitales ✨🎶', help_text='Descripción editable con emojis para el encabezado de la sección de discografía.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Música',
                'verbose_name_plural': 'Configuraciones de Música',
            },
        ),
    ]
