# Generated by Django 5.0.14 on 2026-08-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_musicconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicconfig',
            name='discography_description',
            field=models.TextField(default='Explora las producciones acústicas y sencillos oficiales de Ms. Ambar en todas las plataformas digitales ✨🎶', help_text='Descripción editable con emojis para el encabezado de la sección de discografía.'),
        ),
    ]
