# Generated by Django 5.0.14 on 2026-08-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_musicconfig_discography_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la lista de reproducción o widget', max_length=255)),
                ('platform', models.CharField(blank=True, choices=[('spotify', 'Spotify'), ('youtube', 'YouTube'), ('apple_music', 'Apple Music'), ('amazon_music', 'Amazon Music')], default='spotify', help_text='Plataforma de streaming', max_length=50, null=True)),
                ('render_type', models.CharField(blank=True, choices=[('iframe', 'Iframe Embebido'), ('api_sync', 'Sincronización por API')], default='iframe', help_text='Modo de renderizado (Iframe o API)', max_length=50, null=True)),
                ('embed_url', models.TextField(blank=True, default='', help_text='URL del iframe embebido para Spotify / YouTube / etc.')),
                ('external_id', models.CharField(blank=True, default='', help_text='ID externo de playlist / colección en la plataforma', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Descripción o notas del widget')),
                ('is_active', models.BooleanField(default=True, help_text='Mostrar en el sitio público')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lista de Reproducción',
                'verbose_name_plural': 'Listas de Reproducción',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='musicconfig',
            name='amazon_music_artist_id',
            field=models.CharField(blank=True, default='', help_text='ID o enlace base de artista/afiliado en Amazon Music', max_length=255),
        ),
        migrations.AddField(
            model_name='musicconfig',
            name='apple_music_region',
            field=models.CharField(blank=True, default='us', help_text='Código de región de Apple Music / iTunes (ej: us, mx)', max_length=10),
        ),
        migrations.AddField(
            model_name='musicconfig',
            name='spotify_client_id',
            field=models.CharField(blank=True, default='', help_text='Spotify Client ID', max_length=255),
        ),
        migrations.AddField(
            model_name='musicconfig',
            name='spotify_client_secret',
            field=models.CharField(blank=True, default='', help_text='Spotify Client Secret', max_length=255),
        ),
        migrations.AddField(
            model_name='musicconfig',
            name='youtube_api_key',
            field=models.CharField(blank=True, default='', help_text='YouTube Data API Key', max_length=255),
        ),
    ]
