# Generated by Django 5.0.14 on 2026-06-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_stripeevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='ID del precio en Stripe', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='ID del producto en Stripe', max_length=255, null=True),
        ),
    ]
