# Generated by Django 5.0.14 on 2026-06-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_stripe_price_id_product_stripe_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', help_text='Teléfono del cliente', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='', max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_label_pdf',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_provider',
            field=models.CharField(blank=True, help_text='Ej: FedEx, DHL', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='', max_length=100, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='order',
            name='street_and_number',
            field=models.TextField(default='', help_text='Calle, número exterior e interior'),
        ),
        migrations.AddField(
            model_name='order',
            name='suburb',
            field=models.CharField(default='', max_length=255, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='País'),
        ),
    ]
