# Generated by Django 5.0.14 on 2026-09-04 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_shipping_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopShippingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_mode', models.CharField(choices=[('quotation', 'Cotización en Tiempo Real (Multi-Carrier con rate_id)'), ('direct_rate', 'Envío Directo sin Cotizar (rate/shipments/)')], default='quotation', help_text='Método logístico activo para el checkout y emisión en Skydropx', max_length=30)),
                ('default_carrier', models.CharField(default='fedex', help_text='Carrier predeterminado para envíos directos sin cotizar (ej. fedex, dhl, estafeta)', max_length=50)),
                ('default_service', models.CharField(default='standard_overnight', help_text='Código de servicio predeterminado del carrier (ej. standard_overnight, express)', max_length=50)),
                ('allow_customer_carrier_selection', models.BooleanField(default=True, help_text='Permite al comprador elegir la tarifa y transportista en el checkout si está en modo cotización')),
                ('auto_advance_sandbox', models.BooleanField(default=False, help_text='Habilita auto_advance: true en Sandbox para simular avance de tracking automático por minuto')),
                ('min_balance_alert', models.DecimalField(decimal_places=2, default=500.0, help_text='Umbral de saldo en pesos para emitir alertas de recarga preventiva', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Envíos',
                'verbose_name_plural': 'Configuración de Envíos',
            },
        ),
        migrations.CreateModel(
            name='SkydropxWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento Webhook de Skydropx',
                'verbose_name_plural': 'Webhooks Skydropx',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_attempt_id',
            field=models.CharField(blank=True, db_index=True, help_text='Clave de idempotencia y correlación única para el intento de emisión', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_error',
            field=models.TextField(blank=True, help_text='Detalle del último error o advertencia logística', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('requested', 'Solicitado'), ('processing', 'Procesando (HTTP 202)'), ('created', 'Creado (Tracking Asignado)'), ('label_pending', 'Guía Pendiente de Render'), ('completed', 'Completado (Guía Lista)'), ('failed', 'Fallido'), ('reconciliation_required', 'Requiere Reconciliación'), ('cancelled', 'Cancelado')], db_index=True, default='pending', help_text='Estado granular de emisión y ciclo de vida de la guía en Skydropx', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='skydropx_shipment_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID oficial del shipment en Skydropx', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_id',
            field=models.CharField(blank=True, help_text='ID del envío en Skydropx (compatibilidad)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ShippingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('event_type', models.CharField(choices=[('QUOTE_REQUESTED', 'Cotización Solicitada'), ('QUOTE_RECEIVED', 'Cotización Recibida'), ('SHIPMENT_REQUESTED', 'Emisión Solicitada'), ('SHIPMENT_ACCEPTED_202', 'Emisión Aceptada (HTTP 202)'), ('SHIPMENT_CREATED_SYNC', 'Emisión Inmediata (HTTP 200/201)'), ('POLLING_ATTEMPT', 'Intento de Polling'), ('LABEL_AVAILABLE', 'Guía PDF Disponible'), ('TRACKING_UPDATED', 'Tracking Actualizado'), ('SHIPMENT_CANCELLED', 'Envío Cancelado'), ('SHIPMENT_FAILED', 'Emisión Fallida'), ('RECONCILIATION_STARTED', 'Reconciliación Iniciada'), ('RECONCILIATION_COMPLETED', 'Reconciliación Finalizada'), ('WEBHOOK_PROCESSED', 'Webhook Procesado')], db_index=True, max_length=50)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('request_payload_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('balance_before', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_events', to='shop.order')),
            ],
            options={
                'verbose_name': 'Evento de Auditoría de Envío',
                'verbose_name_plural': 'Auditoría de Envíos',
                'ordering': ['-created_at'],
            },
        ),
    ]
