# Generated by Antigravity for Ms Ambar on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_shopshippingconfig_skydropxwebhookevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopshippingconfig',
            name='origin_name',
            field=models.CharField(default='Almacén Oficial Ms Ambar', help_text='Nombre de la persona o contacto remitente', max_length=150),
        ),
        migrations.AddField(
            model_name='shopshippingconfig',
            name='origin_company',
            field=models.CharField(default='Ms Ambar', help_text='Razón social o empresa remitente', max_length=150),
        ),
        migrations.AddField(
            model_name='shopshippingconfig',
            name='origin_phone',
            field=models.CharField(default='6622140000', help_text='Teléfono del remitente (10 dígitos)', max_length=20),
        ),
        migrations.AddField(
            model_name='shopshippingconfig',
            name='origin_email',
            field=models.EmailField(default='contacto@msambar.com', help_text='Correo electrónico oficial del remitente para Skydropx', max_length=254),
        ),
        migrations.AddField(
            model_name='shopshippingconfig',
            name='origin_street',
            field=models.CharField(default='Blvd. Kino 456', help_text='Calle y número exterior/interior del almacén', max_length=255),
        ),
        migrations.AddField(
            model_name='shopshippingconfig',
            name='origin_suburb',
            field=models.CharField(default='Pitic', help_text='Colonia o asentamiento del remitente', max_length=100),
        ),
        migrations.AddField(
            model_name='shopshippingconfig',
            name='origin_city',
            field=models.CharField(default='Hermosillo', help_text='Ciudad o municipio del remitente', max_length=100),
        ),
        migrations.AddField(
            model_name='shopshippingconfig',
            name='origin_state',
            field=models.CharField(default='Sonora', help_text='Estado de la república del remitente', max_length=100),
        ),
        migrations.AddField(
            model_name='shopshippingconfig',
            name='origin_postal_code',
            field=models.CharField(default='83150', help_text='Código postal del remitente (5 dígitos)', max_length=10),
        ),
    ]
