# Generated by Django 5.0.14 on 2026-09-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_add_origin_address_to_shopshippingconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('creating', 'Creando (En emisión)'), ('requested', 'Solicitado'), ('processing', 'Procesando (HTTP 202)'), ('created', 'Creado (Tracking Asignado)'), ('label_pending', 'Guía Pendiente de Render'), ('completed', 'Completado (Guía Lista)'), ('failed', 'Fallido'), ('reconciliation_required', 'Requiere Reconciliación'), ('unknown', 'Estado Desconocido'), ('cancelled', 'Cancelado')], db_index=True, default='pending', help_text='Estado granular de emisión y ciclo de vida de la guía en Skydropx', max_length=30),
        ),
    ]
