# Generated by Django 5.0.14 on 2026-09-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_order_shipping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packaging_type',
            field=models.CharField(choices=[('box', 'Caja'), ('bag', 'Bolsa')], default='box', help_text='Tipo de empaque seleccionado para el despacho (box: Caja 4G, bag: Bolsa 5M)', max_length=20),
        ),
        migrations.AddField(
            model_name='shopshippingconfig',
            name='bag_height',
            field=models.FloatField(default=5.0, help_text='Alto de bolsa en cm'),
        ),
        migrations.AddField(
            model_name='shopshippingconfig',
            name='bag_length',
            field=models.FloatField(default=30.0, help_text='Largo de bolsa en cm'),
        ),
        migrations.AddField(
            model_name='shopshippingconfig',
            name='bag_weight',
            field=models.FloatField(default=0.5, help_text='Peso base de bolsa en kg'),
        ),
        migrations.AddField(
            model_name='shopshippingconfig',
            name='bag_width',
            field=models.FloatField(default=20.0, help_text='Ancho de bolsa en cm'),
        ),
        migrations.AddField(
            model_name='shopshippingconfig',
            name='box_height',
            field=models.FloatField(default=15.0, help_text='Alto de caja en cm'),
        ),
        migrations.AddField(
            model_name='shopshippingconfig',
            name='box_length',
            field=models.FloatField(default=35.0, help_text='Largo de caja en cm'),
        ),
        migrations.AddField(
            model_name='shopshippingconfig',
            name='box_weight',
            field=models.FloatField(default=1.0, help_text='Peso base de caja en kg'),
        ),
        migrations.AddField(
            model_name='shopshippingconfig',
            name='box_width',
            field=models.FloatField(default=25.0, help_text='Ancho de caja en cm'),
        ),
        migrations.AddField(
            model_name='shopshippingconfig',
            name='default_packaging_type',
            field=models.CharField(choices=[('box', 'Caja'), ('bag', 'Bolsa')], default='box', help_text='Tipo de empaque por defecto para cotizaciones y envíos (box: Caja 4G, bag: Bolsa 5M)', max_length=20),
        ),
    ]
