# Generated by Django 5.0.14 on 2026-09-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_packaging_type_shopshippingconfig_bag_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, help_text='Fecha estimada de entrega oficial reportada por la paquetería', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_history',
            field=models.JSONField(blank=True, default=list, help_text='Historial cronológico de checkpoints del paquete reportados por la paquetería'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_last_checked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp del último sondeo exitoso contra la paquetería/Skydropx', null=True),
        ),
    ]
