# Generated by Django 5.0.14 on 2026-08-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('media_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video')], max_length=10, verbose_name='Tipo de Media')),
                ('provider', models.CharField(choices=[('cloudinary', 'Cloudinary'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('vimeo', 'Vimeo'), ('external', 'Externo / Directo')], default='cloudinary', max_length=20, verbose_name='Proveedor')),
                ('url', models.URLField(max_length=1000, verbose_name='URL Original')),
                ('optimized_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL Optimizada')),
                ('streaming_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL de Streaming (HLS)')),
                ('embed_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL de Incrustación')),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL de Miniatura')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Externo (YouTube ID, etc.)')),
                ('public_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cloudinary Public ID')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ancho')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Alto')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Duración (segundos)')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Elemento de Galería',
                'verbose_name_plural': 'Elementos de Galería',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
