# Generated by Django 5.0.14 on 2026-05-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='event',
            name='mg_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='mg_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='price_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='seat',
            name='position',
            field=models.CharField(choices=[('front', 'Frontal'), ('side_left', 'Lateral Izquierda'), ('side_right', 'Lateral Derecha'), ('back', 'Posterior')], default='front', max_length=20),
        ),
        migrations.AddField(
            model_name='seat',
            name='section',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='has_mg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seat',
            name='category',
            field=models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('general_a', 'General A'), ('general_b', 'General B'), ('accessible', 'Accessible')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='theater',
            name='layout',
            field=models.JSONField(help_text='JSON representation of sections and rows'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('theater', 'section', 'row', 'number')},
        ),
    ]
