# Generated by Django 5.0.14 on 2026-05-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_seat_unique_together_event_mg_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='angle',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='seat',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='seat',
            name='y',
            field=models.FloatField(default=0),
        ),
    ]
