# Generated by Django 5.0.14 on 2026-05-14 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_seat_angle_seat_x_seat_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('blocked', 'Blocked')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='category',
            field=models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP Gold'), ('premium', 'Premium'), ('disabled', 'Accessible')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.seat'),
        ),
        migrations.CreateModel(
            name='GADeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP Gold'), ('premium', 'Premium'), ('disabled', 'Accessible')], default='standard', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_zones', to='tickets.theater')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='ga_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.gadeclaration'),
        ),
    ]
