# Generated by Django 5.0.14 on 2026-06-03 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_fix_theater_layout_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('concert', 'Concierto / Venue'), ('meet_greet', 'Meet & Greet (Convivencia)')], default='concert', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='theater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tickets.theater'),
        ),
    ]
