# Generated by Django 5.0.14 on 2026-06-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_event_event_type_alter_event_theater'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='ID del precio en Stripe (solo para Meet & Greet o general)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='ID del producto en Stripe para este evento', max_length=255, null=True),
        ),
    ]
