# Generated by Django 5.0.14 on 2026-06-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_event_stripe_price_id_event_stripe_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_page_subtitle', models.TextField(default='Selecciona tu concierto, explora el mapa de asientos interactivo y reserva tus boletos oficiales.', help_text='Subtítulo que aparece en la página de compra de boletos (comprar-boletos).')),
                ('homepage_cta_text', models.TextField(default='¡Próximamente nuevo evento!', help_text='Texto del badge de próximo evento en la landing page cuando no hay eventos programados.')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='flyer',
            field=models.ImageField(blank=True, help_text='Imagen del flyer oficial del evento. Se muestra en la landing page y en la página de compra de boletos.', null=True, upload_to='event_flyers/'),
        ),
    ]
