# Generated by Django 5.0.14 on 2026-06-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_sitesettings_event_flyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='stripe_session_id',
            field=models.CharField(blank=True, help_text='ID de la sesión de checkout de Stripe', max_length=255, null=True),
        ),
    ]
