# Generated by Django 5.0.14 on 2026-06-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_event_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.CharField(default='alguna parte del mundo.', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='doors_open',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=120, help_text='Duración estimada del evento en minutos. Útil para calcular la hora de finalización.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_address',
            field=models.CharField(default='por definir', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(default='por definir', max_length=255),
            preserve_default=False,
        ),
    ]
