# Generated by Django 5.0.14 on 2026-07-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_event_slug_alter_event_doors_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
