# Generated by Django 5.0.14 on 2026-07-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_theater_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
