# Generated by Django on 2026-07-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_event_venue_address_alter_event_venue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_seatless_tickets',
            field=models.BooleanField(default=True, help_text='Permite la compra de boletos generales sin asiento reservado'),
        ),
        migrations.AddField(
            model_name='event',
            name='seatless_ticket_price',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Precio base de boleto general sin asiento', max_digits=10),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único del cupón (ej. VIP-AMBAR-2026)', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('free_vip', 'Entrada Gratuita VIP (100% Descuento)'), ('percentage', 'Porcentaje de Descuento'), ('fixed', 'Monto Fijo de Descuento')], default='free_vip', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=100.0, help_text='Porcentaje (0-100) o monto fijo en MXN', max_digits=7)),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='Límite de redenciones del cupón')),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Veces que ha sido redimido')),
                ('is_active', models.BooleanField(default=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, help_text='Evento específico (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='tickets.event')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='used_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.coupon'),
        ),
    ]
