# Generated by Django 5.0.14 on 2026-07-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_coupon_assigned_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enable_dynamic_pricing',
            field=models.BooleanField(default=True, help_text='Activa el ajuste dinámico mensual de precios previo al evento'),
        ),
        migrations.AddField(
            model_name='event',
            name='monthly_price_increment',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Monto de incremento mensual (ej. $50.00 MXN)', max_digits=10),
        ),
    ]
