# Generated by Django 5.0.14 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_sanitize_event_prices_and_dynamic_floors'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
