# Generated by Django 5.0.14 on 2026-07-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_seat_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='color',
        ),
    ]
