# Generated by Django 5.0.14 on 2026-07-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_seat_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='numbered_ticket_price',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text='Precio base de boleto numerado reservado', max_digits=10),
        ),
    ]
