# Generated by Django 5.0.14 on 2026-07-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_event_numbered_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accent_color',
            field=models.CharField(blank=True, help_text='Color de resplandor / detalles (ej. #9F2B00)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='background_end',
            field=models.CharField(blank=True, help_text='Color fin degradado fondo (ej. #040605)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='background_pattern',
            field=models.CharField(blank=True, choices=[('stars', 'Estrellas Doradas Flotantes'), ('grid', 'Malla Geométrica Futurista'), ('dots', 'Puntos Sutiles Minimalistas'), ('waves', 'Ondas Gradientes Suaves'), ('none', 'Limpio (Solo degradado)')], help_text='Patrón visual de fondo', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='background_start',
            field=models.CharField(blank=True, help_text='Color inicio degradado fondo (ej. #080c0a)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='card_background',
            field=models.CharField(blank=True, help_text='Color de fondo de tarjetas de cristal (ej. #0c0f0d)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='card_style',
            field=models.CharField(blank=True, choices=[('rounded-full', 'Ultra Suave / Redondeado Total (Píldoras y Cristal)'), ('rounded-2xl', 'Moderno (Esquinas Medias Elegantes)'), ('rounded-lg', 'Clásico (Esquinas Sutiles)'), ('rounded-none', 'Recto / Neobrutalismo')], help_text='Estilo de bordes de tarjetas y botones', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='custom_css',
            field=models.TextField(blank=True, help_text='CSS personalizado para este evento específico', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='font_preset',
            field=models.CharField(blank=True, choices=[('cormorant', 'Cormorant Garamond (Elegante & Místico)'), ('outfit', 'Outfit / Inter (Moderno & Tecnológico)'), ('cinzel', 'Cinzel Decorative (Editorial & Lujo)'), ('syne', 'Syne (Vanguardista & Artístico)')], help_text='Preset de fuentes tipográficas', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='particle_shape',
            field=models.CharField(blank=True, choices=[('circle', 'Círculo (Mundo)'), ('moon', 'Media Luna'), ('cactus', 'Cactus / Desierto'), ('star', 'Estrella (Brillo)'), ('infinity', 'Símbolo Infinito'), ('hexagon', 'Hexágono Futuro'), ('sun', 'Sol Radiante'), ('wave', 'Ondas Fluídas'), ('spiral', 'Espiral Mística'), ('music', 'Nota Musical'), ('eye', 'Ojo / Visión'), ('love', 'Corazón / Amor'), ('bee', 'Abeja / Colmena'), ('eclipse', 'Eclipse Sombra'), ('none', 'Partículas Libres (Sin forma)')], help_text='Figura geométrica del Canvas de partículas', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Color primario de acentos, botones y luces (ej. #E5A93B). Dejar en blanco para usar configuración global.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='secondary_color',
            field=models.CharField(blank=True, help_text='Color secundario (ej. #22A6B7)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='section_themes',
            field=models.JSONField(blank=True, default=dict, help_text='Configuración visual granular por sección (Hero, Boletos, Mapa, Contacto, Tarot, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='text_color',
            field=models.CharField(blank=True, help_text='Color principal del texto (ej. #F4F6F0)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#9F2B00', help_text='Color de resplandor / detalles (ej. #9F2B00)', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='background_end',
            field=models.CharField(default='#040605', help_text='Color fin degradado fondo (ej. #040605)', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='background_pattern',
            field=models.CharField(choices=[('stars', 'Estrellas Doradas Flotantes'), ('grid', 'Malla Geométrica Futurista'), ('dots', 'Puntos Sutiles Minimalistas'), ('waves', 'Ondas Gradientes Suaves'), ('none', 'Limpio (Solo degradado)')], default='stars', help_text='Patrón visual de fondo', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='background_start',
            field=models.CharField(default='#080c0a', help_text='Color inicio degradado fondo (ej. #080c0a)', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='card_background',
            field=models.CharField(default='#0c0f0d', help_text='Color de fondo de tarjetas de cristal (ej. #0c0f0d)', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='card_style',
            field=models.CharField(choices=[('rounded-full', 'Ultra Suave / Redondeado Total (Píldoras y Cristal)'), ('rounded-2xl', 'Moderno (Esquinas Medias Elegantes)'), ('rounded-lg', 'Clásico (Esquinas Sutiles)'), ('rounded-none', 'Recto / Neobrutalismo')], default='rounded-full', help_text='Estilo de bordes de tarjetas y botones', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='custom_css',
            field=models.TextField(blank=True, default='', help_text='CSS personalizado global para todo el sitio', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='font_preset',
            field=models.CharField(choices=[('cormorant', 'Cormorant Garamond (Elegante & Místico)'), ('outfit', 'Outfit / Inter (Moderno & Tecnológico)'), ('cinzel', 'Cinzel Decorative (Editorial & Lujo)'), ('syne', 'Syne (Vanguardista & Artístico)')], default='cormorant', help_text='Preset de fuentes tipográficas', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='particle_shape',
            field=models.CharField(choices=[('circle', 'Círculo (Mundo)'), ('moon', 'Media Luna'), ('cactus', 'Cactus / Desierto'), ('star', 'Estrella (Brillo)'), ('infinity', 'Símbolo Infinito'), ('hexagon', 'Hexágono Futuro'), ('sun', 'Sol Radiante'), ('wave', 'Ondas Fluídas'), ('spiral', 'Espiral Mística'), ('music', 'Nota Musical'), ('eye', 'Ojo / Visión'), ('love', 'Corazón / Amor'), ('bee', 'Abeja / Colmena'), ('eclipse', 'Eclipse Sombra'), ('none', 'Partículas Libres (Sin forma)')], default='moon', help_text='Figura geométrica del Canvas de partículas', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#E5A93B', help_text='Color primario de acentos, botones y luces (ej. #E5A93B)', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#22A6B7', help_text='Color secundario (ej. #22A6B7)', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_themes',
            field=models.JSONField(blank=True, default=dict, help_text='Configuración visual granular por sección del sitio (Hero, Boletos, Mapa, Contacto, Tarot, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='text_color',
            field=models.CharField(default='#F4F6F0', help_text='Color principal del texto (ej. #F4F6F0)', max_length=50),
        ),
    ]
