# Generated by Django 5.0.14 on 2026-07-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_event_accent_color_event_background_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='theme_mode',
            field=models.CharField(default='global', help_text="Modo de aplicación de tema: 'global' o 'section'", max_length=20),
        ),
    ]
