# Generated by Django 5.0.14 on 2026-07-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_event_allow_numbered_tickets'),
        ('tickets', '0023_sitesettings_theme_mode'),
    ]

    operations = [
    ]
