# Generated by Django 5.0.14 on 2026-07-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_sitesettings_theme_mode'),
    ]

    operations = [
        # Bio fields already added in 0018_sitesettings_bio_fields.py
    ]
