# Generated by Django 5.0.14 on 2026-07-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_sitesettings_bio_fields'),
        ('tickets', '0024_merge_20260730_1153'),
    ]

    operations = [
    ]
