# Generated by Django 5.0.14 on 2026-07-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_merge_20260730_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='allow_canvas_zoom',
            field=models.BooleanField(default=True, help_text='Permite o bloquea el zoom interactivo en el canvas de selección de asientos'),
        ),
    ]
