# Generated by Django 5.0.14 on 2026-07-31 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_sitesettings_bio_badge_sitesettings_bio_content_and_more'),
        ('tickets', '0026_sitesettings_allow_canvas_zoom'),
    ]

    operations = [
    ]
