# Generated by Django 5.0.14 on 2026-07-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_merge_20260730_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pass_fees_to_buyer',
            field=models.BooleanField(default=True, help_text='Si está activo, transfiere el recargo (Gross-Up) del 3.6% + $3.00 MXN al comprador en Checkout para recibir el 100% íntegro de la venta en banco.'),
        ),
    ]
