# Generated by Django 5.0.14 on 2026-07-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_sitesettings_pass_fees_to_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto real cobrado por el boleto al momento de la compra', max_digits=10, null=True),
        ),
    ]
