# Generated by Django 5.0.14 on 2026-08-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_ticket_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='button_focus_ring',
            field=models.CharField(default='#E5A93B', help_text='Color de anillo focus en botones', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='button_hover_bg',
            field=models.CharField(default='#FFC048', help_text='Color de fondo hover en botones', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='button_hover_text',
            field=models.CharField(default='#080c0a', help_text='Color de texto hover en botones', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='card_focus_ring',
            field=models.CharField(default='#22A6B7', help_text='Color de anillo focus en tarjetas', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='card_hover_bg',
            field=models.CharField(default='#121714', help_text='Color de fondo hover en tarjetas', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='card_hover_border',
            field=models.CharField(default='#E5A93B', help_text='Color de borde hover en tarjetas', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='element_focus_ring',
            field=models.CharField(default='#E5A93B', help_text='Color focus para elementos interactivos', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='element_hover_color',
            field=models.CharField(default='#FFC048', help_text='Color hover para elementos interactivos', max_length=50),
        ),
    ]
