# Generated by Django 5.0.14 on 2026-08-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_sitesettings_button_focus_ring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='background_gradient',
            field=models.CharField(blank=True, default='', help_text='Degradado CSS de fondo (ej. linear-gradient(135deg, #080c0a 0%, #040605 100%))', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='border_opacity',
            field=models.FloatField(blank=True, default=0.25, help_text='Opacidad de borde de 0.0 a 1.0', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='border_style_preset',
            field=models.CharField(blank=True, default='solid', help_text='Estilo de borde (solid, glass, dashed, dotted)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='border_width',
            field=models.CharField(blank=True, default='1px', help_text='Grosor de borde de contenedor (ej. 1px, 2px)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='card_box_shadow',
            field=models.CharField(blank=True, default='', help_text='Sombra dinámica de tarjetas (ej. 0 10px 30px rgba(0,0,0,0.5))', max_length=255, null=True),
        ),
    ]
