# Generated by Django 5.0.14 on 2026-08-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0031_sitesettings_background_gradient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='particle_color',
            field=models.CharField(blank=True, help_text='Color de partículas (ej. #E5A93B)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='particle_density',
            field=models.IntegerField(blank=True, default=65, help_text='Densidad de partículas (10 a 200)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='particle_speed',
            field=models.FloatField(blank=True, default=1.0, help_text='Velocidad de partículas (0.1 a 5.0)', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='particle_color',
            field=models.CharField(blank=True, default='', help_text='Color de partículas (ej. #E5A93B)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='particle_density',
            field=models.IntegerField(default=65, help_text='Densidad de partículas (10 a 200)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='particle_speed',
            field=models.FloatField(default=1.0, help_text='Velocidad de partículas (0.1 a 5.0)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='particle_shape',
            field=models.CharField(blank=True, choices=[('circle', 'Círculo (Mundo)'), ('moon', 'Media Luna'), ('cactus', 'Cactus / Desierto'), ('star', 'Estrella (Brillo)'), ('triangle', 'Triángulo Místico'), ('polygon', 'Polígono Geométrico'), ('infinity', 'Símbolo Infinito'), ('hexagon', 'Hexágono Futuro'), ('sun', 'Sol Radiante'), ('wave', 'Ondas Fluídas'), ('spiral', 'Espiral Mística'), ('music', 'Nota Musical'), ('eye', 'Ojo / Visión'), ('love', 'Corazón / Amor'), ('bee', 'Abeja / Colmena'), ('eclipse', 'Eclipse Sombra'), ('none', 'Partículas Libres (Sin forma)')], help_text='Figura geométrica del Canvas de partículas', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='particle_shape',
            field=models.CharField(choices=[('circle', 'Círculo (Mundo)'), ('moon', 'Media Luna'), ('cactus', 'Cactus / Desierto'), ('star', 'Estrella (Brillo)'), ('triangle', 'Triángulo Místico'), ('polygon', 'Polígono Geométrico'), ('infinity', 'Símbolo Infinito'), ('hexagon', 'Hexágono Futuro'), ('sun', 'Sol Radiante'), ('wave', 'Ondas Fluídas'), ('spiral', 'Espiral Mística'), ('music', 'Nota Musical'), ('eye', 'Ojo / Visión'), ('love', 'Corazón / Amor'), ('bee', 'Abeja / Colmena'), ('eclipse', 'Eclipse Sombra'), ('none', 'Partículas Libres (Sin forma)')], default='moon', help_text='Figura geométrica del Canvas de partículas', max_length=50),
        ),
    ]
