# Generated by Django 5.0.14 on 2026-08-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_event_particle_color_event_particle_density_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='particle_shadow',
            field=models.CharField(blank=True, default='', help_text='Color/Efecto de sombra de partículas (ej. #E5A93B o rgba(229,169,59,0.8))', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='particle_shadow',
            field=models.CharField(blank=True, default='', help_text='Color/Efecto de sombra de partículas (ej. #E5A93B o rgba(229,169,59,0.8))', max_length=100, null=True),
        ),
    ]
