# Generated by Django 5.0.14 on 2026-09-27 17:04

import apps.tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_event_particle_shadow_sitesettings_particle_shadow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='flyer',
            field=models.ImageField(blank=True, help_text='Imagen del flyer oficial del evento. Se muestra en la landing page y en la página de compra de boletos.', max_length=500, null=True, upload_to=apps.tickets.models.event_flyer_upload_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.tickets.models.event_image_upload_path),
        ),
    ]
