# Generated by Django 5.0.14 on 2026-09-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_event_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='allowed_emails',
            field=models.JSONField(blank=True, default=list, help_text='Lista de correos autorizados para redimir este cupón'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='complimentary_allocation_mode',
            field=models.CharField(choices=[('OPEN', 'Asignación Abierta (Cualquier Fila/Zona)'), ('DESIGNATED_ROW', 'Fila Designada Específica (Prioridad)')], default='OPEN', help_text='Modo de asignación de asiento para cortesías', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_complimentary',
            field=models.BooleanField(default=False, help_text='Marca el cupón como cortesía de cortesía/prensa/invitados especiales'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='requires_seat',
            field=models.BooleanField(default=True, help_text='Indica si el cupón requiere reservar asiento numerado en el mapa'),
        ),
        migrations.AddField(
            model_name='event',
            name='complimentary_rows_priority',
            field=models.JSONField(blank=True, default=list, help_text='Lista priorizada de filas para cortesía en este evento (sobrescribe la del teatro si se define)'),
        ),
        migrations.AddField(
            model_name='theater',
            name='complimentary_rows_priority',
            field=models.JSONField(blank=True, default=list, help_text="Lista priorizada de filas designadas para cortesía (ej. ['Fila G', 'Fila H'])"),
        ),
    ]
