# Generated by Django 5.0.14 on 2026-10-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0040_event_cutoff_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='timezone',
            field=models.CharField(default='America/Hermosillo', help_text='Zona horaria IANA del teatro/venue (ej. America/Hermosillo).', max_length=50),
        ),
    ]
